# Generated by Django 5.2.6 on 2025-09-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(unique=True)),
                ('company_name', models.CharField()),
                ('shipping_address', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Pepito', 'Pepito'), ('Cornet', 'Cornet'), ('Cuneta', 'Cuneta')], default='Pepito')),
                ('product_type', models.CharField(choices=[('Pepito', 'Pepito'), ('Cornet', 'Cornet'), ('Cuneta', 'Cuneta')], default='Pepito')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')])),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('additional_info', models.TextField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
                ('item', models.ManyToManyField(through='sales.OrderProduct', to='sales.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
    ]
